config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  resources :users
  resources :kicks

  root 'home#index'
end

app/models/kick.rb
class Kick < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :kicks

  validates :password, presence: true, on: :create, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kicks_controller.rb
class KicksController < ApplicationController
  def index
    @kicks = Kick.all
  end

  def show
    @kick = Kick.find_by_id(params[:email][:id])
  end

  def new
    @kick = Kick.new 
  end

  def create
    @kick = Kick.new(kick_params)

    if @kicks.save
      flash[:notice] = "Kicks were successfully created!"
      redirect_to kicks_path
    else
      flash.now[:alert] = "Could not create your Kicks."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:sign_in][:email])
    if user && user.authenticate(params[:sign_in][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Invalid email & password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @users = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password_digest, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kicks_helper.rb
module KicksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1> home/index.html.erb page</h1>

app/views/kicks/edit.html.erb
<h1>Kicks#edit</h1>
<p>Find me in app/views/kicks/edit.html.erb</p>

app/views/kicks/index.html.erb
<h1>Kicks#index</h1>
<p>Find me in app/views/kicks/index.html.erb</p>

app/views/kicks/new.html.erb
<div class="row">
  <div class="col-md-10">
    <%= simple_form_for @kick do |f| %>

      <%= f.input :brand, label: 'Brand:' %>
      <%= f.input :brand, label: 'Model:' %>
      <%= f.input :colorway, label: 'Colorway:' %>
      <%= f.input :lowmidhigh, label: 'Low, Mid, or High?:' %>
      <%= f.input :price %>
      <%= f.input :forsale %>
      <%= f.button :submit, label: 'Add Kicks!' %>
    <% end %>  
  </div>
</div>

app/views/kicks/show.html.erb
<h1>Kicks#show</h1>
<p>Find me in app/views/kicks/show.html.erb</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #A8A8A8;"> 
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ricks Kicks', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li id="user-email"> <%= current_user.email %></li>
          <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <section>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </section>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>